q = input("please enter first number ")
x = input("please enter second number ")
addition = int(q) + int(x)
print(addition)
subtraction = int(q) - int(x)
print(subtraction)
multiplication = int(q) * int(x)
print(multiplication)
exponential = int(q) ** int(x)
print(exponential)
modulus = int(q) % int(x)
print(modulus)
division = int(q) / int(x)
print(division)
floor_division = int(q) // int(x)
print(floor_division)
